### ISSUE TITLE
As a user, I would like to "Core Features Posts and Feed"

### ISSUE THREAD

**Issue by jbwaring** [jbwaring/Instaframe_2#10]
- access feed to check my own posts
- submit a post
- comment another user's post
- follow another user.

Priority HIGH
Risk HIGH

**Comment by mohsen220** [comment]
Acceptance test attached below for accessing a feed. [
<img width="726" alt="Screen Shot 2021-04-20 at 3 03 39 PM" src="https://user-images.githubusercontent.com/68242902/115450484-f08a9d00-a1e9-11eb-9939-9fb441827e4d.png">
](url)
