### ISSUE TITLE
As a user, I want to retrieve my password in case I forgot.

### ISSUE THREAD

**Issue by jbwaring** [jbwaring/Instaframe_2#11]
Forgot password

Priority LOW
Risk LOW

**Comment by jbwaring** [comment]
Task Breakdown:
"I forgot" view already exists.

- enter email
- check email exists in the database through API Call
- handle errors through a modal alert 
- send email to address with instructions.

**Comment by mohsen220** [comment]
Acceptance test attached below. 
<img width="859" alt="Screen Shot 2021-04-11 at 4 24 16 PM" src="https://user-images.githubusercontent.com/68242902/114320116-6902a700-9ae2-11eb-9f6a-185244a751c6.png">

**Comment by mohsen220** [comment]
***Error with tool mentioned: BITRISE NOT JENKINS.

**Comment by mohsen220** [comment]
Story point: 0.5
