### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by jbwaring** [jbwaring/Instaframe_2#13]
As a dev, I want to have continuous Integration on the App at each commit.

**Comment by jbwaring** [comment]
Travis CI is implemented on branch UnitTest. Need to create merge request to main to get .yml to main and then have all branches on CI.

**Comment by mohsen220** [comment]
What unit tests do you have set up so far? @jbwaring

**Comment by jbwaring** [comment]
Login, Signup, Forgot Password ~ 10 tests

**Comment by jbwaring** [comment]
The trouble of running UnitTests on SwiftUI and using CI is solved. Using External UnitTest Library ViewInspector and TravisCI.
Issue shall be closed.
