### ISSUE TITLE
As a user I would like to be able to "like" another post 

### ISSUE THREAD

**Issue by mohsen220** [jbwaring/Instaframe_2#15]
Steps:
-App must be able to identify that the user is following  the designated person with the post.  Set up user-interface to allow users to brows through the feed and click the "like" icon. 
-Backend has to be implemented to retrieve and monitor post likes. 
- Set up the logic and link it to the CloudKit database. 

Priority: HIGH

**Comment by jbwaring** [comment]
Like Feature is implemented and works with the backend as well. 
Issue is closed.

**Comment by mohsen220** [comment]
Story points: 1
