### ISSUE TITLE
As a user, I would like to view my follower/following count. 

### ISSUE THREAD

**Issue by mohsen220** [jbwaring/Instaframe_2#21]
Steps: 
- Fetch user profile, and append their followedBy array and following array. 
- Display it accordingly on the app, i.e modifying the UI to showcase the actual count and usernames. 

Priority: high 
Risk: high

**Comment by jbwaring** [comment]
The issue is partially implemented. Some bugs need to be fixed before the final presentation. The issue remains open.

**Comment by jbwaring** [comment]
Feature is implemented. Issue is closed.
