### ISSUE TITLE
As a user, I want to follow another user

### ISSUE THREAD

**Issue by mohsen220** [jbwaring/Instaframe_2#3]
Description: As a user, I want to be able to follow another user so that I can see his posts in the future.

Steps:

Unfollow: user can unfollow another user he followed once
User can see his/her number of followers and the followers' usernames
User can see the posts of who the user follows based on the post's recency
Follow schema in database
User can search for users to follow
Priority: HIGH

**Comment by jbwaring** [comment]
Task Breakdown:

 - create "followedBy" propriety 
 - when user is followed, following user_id is added to the array followedBy of followed user
 - number of followers is User.followedBy?.count
 - If no followers, followedBy will be nil -> handle this by using optional unwrapping of value when needed  (User.followedBy?.count ?? 0)
 - Who follows me can be implemented by searching the userbase for the ids listed in followedBy

**Comment by mohsen220** [comment]
The Home feed has been set up already, you can now press a follow button that allows you to follow another user. The back-end still needs some work though. 
-> We still need to link it to firebase and make sure that the posts displayed in the profile feed are ones that actually belong to the user.

**Comment by jbwaring** [comment]
OK. Have you linked the HomeFeedView to the ContentView TabView?

**Comment by mohsen220** [comment]
Working on it as we speak, ran into some problems but it should be done in the next hour or so.

**Comment by jbwaring** [comment]
Don't forget to pass the environment variable ;)

**Comment by mohsen220** [comment]
Done! @jbwaring

**Comment by jbwaring** [comment]
Issue is duplicate. another issue supports both Follow/ Get Followed.
Issue is closed.

**Comment by mohsen220** [comment]
Story points: 2
