### ISSUE TITLE
As a User, I want to access my profile feed to check my posts 

### ISSUE THREAD

**Issue by mohsen220** [jbwaring/Instaframe_2#6]
Description: As a user, I want to be able to navigate the UI appropriately and have an option where I could access my own profile page and check my posts. 

Steps:

- Using SwiftUI to design the front-end and design of the page. This involves positioning the profile icon, Bio, follower/following/post count and the posts previously posted by the user. 
- User will be able to view all posts and write a small bio in addition to the checking follower/following counts . 
- Setting the database schema (i.e CloudKit).

Priority:
HIGH

**Comment by jbwaring** [comment]
Task Breakdown:

- Initial offline design of the view
- Important: Effective adaptive layout for the view needs to work for 0 posts, 1 posts and 1000+ posts.
- Quick Links to settings and follower lists.
- Live Data test of the view
- add view to the TabView in home
- pass CoreData/CloudKit managedContext to view

**Comment by jbwaring** [comment]
Main View design is done. Shall pass environment variable and merge with master soon.

**Comment by mohsen220** [comment]
Issue closed!

**Comment by mohsen220** [comment]
Acceptance test attached below. [
<img width="731" alt="Screen Shot 2021-04-20 at 2 55 45 PM" src="https://user-images.githubusercontent.com/68242902/115450268-af928880-a1e9-11eb-9943-4537be406737.png">
](url)

**Comment by mohsen220** [comment]
Story points: 2
