### ISSUE TITLE
As a user, I want to change my password

### ISSUE THREAD

**Issue by jbwaring** [jbwaring/Instaframe_2#8]
Change password through settings view and get an email confirmation that password was changed.

Priority: LOW

Part of User-Account Epic.

**Comment by jbwaring** [comment]
Task Breakdown:

- Create Modal change my password view.
- Check current password
- Enter the new password twice and check the appropriate length and does not match the old password.
- API Call to Firebase
- Handle errors
- Confirm change through modal alert and email to say: "your password has been changed".
- Back to settings view.

**Comment by jbwaring** [comment]
Forgot password is implemented and working, added to unit testings.

**Comment by mohsen220** [comment]
Story point: 1
