### ISSUE TITLE
As a user, I want to change my email

### ISSUE THREAD

**Issue by jbwaring** [jbwaring/Instaframe_2#9]
Change email address through settings and get a confirmation on the new selected address.

Priority: LOW.

**Comment by jbwaring** [comment]
Task Breakdown:

- Create Modal change my email view.
- Check current email
- Check new email is a valid email.
- API Call to Firebase
- Handle errors
- Confirm change through modal alert and email to the new address.
- Back to settings view.

**Comment by jbwaring** [comment]
Not yet implemented. Do we want to keep this?

**Comment by mohsen220** [comment]
I don't think it is an important feature that we need to implement, I am going to close it.

**Comment by mohsen220** [comment]
Story point: 0.5
